# Generated by Django 4.0.3 on 2023-04-19 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicalMaterial',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('altaveu', 'ALTAVEU'), ('micròfon', 'MICRÒFON'), ('percussió', 'PERCUSSIÓ'), ('corda', 'CORDA'), ('vent', 'VENT'), ('amplificador', 'AMPLIFICADOR')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MusicalStudio',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('type', models.CharField(choices=[('ensaig', 'ENSAIG'), ('enregistrar', 'ENREGISTRAR')], max_length=100)),
                ('incorporated_material', models.ManyToManyField(blank=True, to='music_engine.musicalmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='technical_personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inici', models.TimeField()),
                ('hora_fi', models.TimeField()),
                ('reservat', models.BooleanField(default=False)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_engine.musicalstudio')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_engine.musicalmaterial')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_engine.musicalstudio')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_engine.technical_personnel')),
            ],
        ),
    ]
