# Generated by Django 4.0.3 on 2023-05-13 18:12

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cognom', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Comercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cognom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MusicalMaterial',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('altaveu', 'ALTAVEU'), ('micròfon', 'MICRÒFON'), ('percussió', 'PERCUSSIÓ'), ('corda', 'CORDA'), ('vent', 'VENT'), ('amplificador', 'AMPLIFICADOR')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MusicalStudio',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('type', models.CharField(choices=[('ensaig', 'ENSAIG'), ('enregistrar', 'ENREGISTRAR')], max_length=100)),
                ('incorporated_material', models.ManyToManyField(blank=True, to='music_engine.musicalmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Receip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('subject', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Receip2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='technical_personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=30)),
                ('specialty', models.CharField(default='none', max_length=50)),
                ('experience', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inici', models.TimeField()),
                ('hora_fi', models.TimeField()),
                ('reservat', models.BooleanField(default=False)),
                ('material', models.ManyToManyField(blank=True, to='music_engine.musicalmaterial')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_engine.musicalstudio')),
                ('tecnic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music_engine.technical_personnel')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HoursRecord',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('hours', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)])),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_engine.reserva')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disponibility',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('available', models.BooleanField(default=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_engine.musicalmaterial')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_engine.musicalstudio')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_engine.technical_personnel')),
            ],
        ),
    ]
