# Generated by Django 4.0.3 on 2023-04-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicalstudio',
            name='incorporated_material',
        ),
        migrations.AddField(
            model_name='musicalstudio',
            name='incorporated_material',
            field=models.ManyToManyField(blank=True, to='music_engine.musicalmaterial'),
        ),
    ]
