# Generated by Django 4.0.3 on 2023-05-15 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoursrecord',
            name='reserva',
        ),
        migrations.AlterField(
            model_name='receip',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_engine.reserva'),
        ),
    ]
