# Generated by Django 4.2 on 2023-04-30 16:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("music_engine", "0002_hoursrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receip2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(default=datetime.date.today, verbose_name="Date"),
                ),
                ("subject", models.CharField(max_length=50)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="music_engine.assignment",
                    ),
                ),
            ],
        ),
    ]
