# Generated by Django 4.2 on 2023-05-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music_engine", "0002_alter_hoursrecord_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="technical_personnel",
            name="experience",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="technical_personnel",
            name="specialty",
            field=models.CharField(default="none", max_length=50),
        ),
    ]
