# Generated by Django 4.0.3 on 2023-05-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_engine', '0003_technical_personnel_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoursrecord',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
