# Generated by Django 4.0.3 on 2023-04-08 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_engine', '0003_remove_technician_user_ptr_delete_resourcemanager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inici', models.TimeField()),
                ('hora_fi', models.TimeField()),
                ('reservat', models.BooleanField(default=False)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_engine.musicalstudio')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
