# Generated by Django 4.1.7 on 2023-05-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_engine', '0003_technical_personnel_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cognom', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
            ],
        ),
    ]
