# Generated by Django 4.1.7 on 2023-04-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_engine', '0004_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='technical_personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=30)),
            ],
        ),
    ]
