# Generated by Django 4.1.7 on 2023-04-10 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_engine', '0004_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='technical_personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_engine.musicalmaterial')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_engine.musicalstudio')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_engine.technical_personnel')),
            ],
        ),
    ]
