# Generated by Django 4.1.7 on 2023-05-04 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_engine', '0004_alter_receip_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicTecnic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnic_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music_engine.technical_personnel')),
            ],
        ),
    ]
