# Generated by Django 4.1.7 on 2023-05-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_engine', '0004_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cognom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
