# Generated by Django 4.2 on 2023-04-09 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_engine', '0005_technical_personnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_engine.musicalmaterial')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_engine.musicalstudio')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_engine.technical_personnel')),
            ],
        ),
    ]
